#!/bin/bash
folder=$1


if [ ! -d "${folder}/cellworld_data" ]; then
  cd "$folder"
  git clone https://github.com/germanespinosa/cellworld_data -–depth 1
fi

echo "export CELLWORLD_CACHE=${folder}/cellworld_data" >> ~/.bashrc

export CELLWORLD_CACHE=${folder}/cellworld_data
