#!/bin/bash
folder=$1

if [ "$folder" == "" ]; then
  echo "Cache destination folder should not be emtpy (try /research)"
  exit 1
fi

if [ ! -d "${folder}/cellworld_data" ]; then
  cd "$folder"
  git clone https://github.com/germanespinosa/cellworld_data
fi

echo "export CELLWORLD_CACHE=${folder}/cellworld_data" >> ~/.bashrc

export CELLWORLD_CACHE=${folder}/cellworld_data
